[workspace]
members = [
    "claim",
    "proof_of_innocence",
    "transfer",
    "split",
    "partial_withdraw",
    "stealth_transfer",
    "helpers",
    "utils",
    "pool_deposit",
    "pool_withdraw",
    "pool_claim_yield"
]
