# Split Circuit Test Inputs
# Private inputs (1 BTC split into 0.6 + 0.4 BTC)
input_nullifier = "12345"
input_secret = "67890"
input_amount = "100000000"
merkle_path = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
path_indices = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
output1_nullifier = "11111"
output1_secret = "22222"
output1_amount = "60000000"
output2_nullifier = "33333"
output2_secret = "44444"
output2_amount = "40000000"

# Public inputs (computed using Poseidon2)
merkle_root = "0x28f4390799e65388aec42df7f5b130431306e33db9cd9ff979852b19ae90a01d"
input_nullifier_hash = "0x1fed07ad686a727dfc33b91206d526e61f519dca9c5054ae729231c201717633"
output_commitment1 = "0x26c88f1889bafc6e78d06bcf787e6a1270042e120cab7f083c6cecb1c4e1fa91"
output_commitment2 = "0x2e82595d39151dcb6161facb3add37cb484d7bf1eda1ee91d5d014af4ac52c01"
