nullifier = "12345"
secret = "67890"
amount = "1000000"
merkle_path = ["0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"]
path_indices = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
merkle_root = "0x2e85ac0d549a4ec46222019fec1f4653462f77c32a3bf40d1fa514dc25af3482"
nullifier_hash = "0x1fed07ad686a727dfc33b91206d526e61f519dca9c5054ae729231c201717633"
amount_pub = "1000000"
