[package]
name = "zvault_proof_of_innocence"
type = "bin"
authors = ["zVault Team"]

[dependencies]
zvault_utils = { path = "../utils" }
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
