[workspace]
resolver = "2"
members = [
    "programs/zvault",
    "programs/btc-light-client",
    "programs/ultrahonk-verifier",
]
exclude = [
    "programs/chadbuffer"
]

[profile.release]
overflow-checks = true
