# Partial Withdraw Circuit Test Inputs
# Private inputs (1 BTC, withdraw 0.3, keep 0.7 as change)
nullifier = "12345"
secret = "67890"
amount = "100000000"
merkle_path = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
path_indices = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
change_nullifier = "11111"
change_secret = "22222"
change_amount = "70000000"

# Public inputs (computed using Poseidon2)
merkle_root = "0x28f4390799e65388aec42df7f5b130431306e33db9cd9ff979852b19ae90a01d"
nullifier_hash = "0x1fed07ad686a727dfc33b91206d526e61f519dca9c5054ae729231c201717633"
withdraw_amount = "30000000"
change_commitment = "0x07e0764478ab9a91add1ec48dcda91d79d3dcbb34503aabb076aacebe90c25c6"
recipient = "99999"
