[package]
name = "zvault_pool_claim_yield"
type = "bin"
authors = ["zVault Team"]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
zvault_utils = { path = "../utils" }
